---
server.port: 7002
logging:
  level:
    root: INFO
    com.agosme: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring.profiles: docker
server.port: 8080
logging:
  level:
    root: INFO
    com.agosme: DEBUG