server.port: 8888
spring.profiles.active: native

spring.cloud.config.server.native.searchLocations: file:/Users/toto/Repo/git/MicroServiceSpringCloud/config-repo
#spring.cloud.config.username: a
#spring.cloud.config.password: a
# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
#management.endpoint.health.show-details: "ALWAYS"
#management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: info
#    com.agosme: debug
#import org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping;
#---
#spring.profiles: docker
#spring.cloud.config.server.native.searchLocations: file:/config-repo



