server.port: 8888
spring.profiles.active: native,devlocal
spring.cloud.config.server.native.searchLocations: file:/Users/toto/Repo/git/MicroServiceSpringCloud/config-repo

# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: info

---
spring.profiles: devlocal
spring.security.user:
  name: dev-usr
  password: dev-pwd

---
spring.profiles: docker
spring.cloud.config.server.native.searchLocations: file:/config-repo


