---
server.port: 7001
spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

logging:
  level:
    root: INFO
    com.agosme: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup
  bindings.input.consumer:
    maxAttempts: 3
    backOffInitialInterval: 500
    backOffMultiplier: 2.0
  rabbit.bindings.input.consumer:
    autoBindDlq: true
    republishToDlq: true
  kafka.bindings.input.consumer:
    enableDlq: true
  kafka.binder:
    brokers: 127.0.0.1
    defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest


---
spring.profiles: docker
server.port: 8080
spring.data.mongodb.host: mongodb
logging:
  level:
    root: INFO
    com.agosme: DEBUG
spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka