---
server.port: 7001
spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

logging:
  level:
    root: INFO
    com.agosme: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring.profiles: docker
server.port: 8080
spring.data.mongodb.host: mongodb
logging:
  level:
    root: INFO
    com.agosme: DEBUG