---
server.port: 7003

spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd
  hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.agosme: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring.profiles: docker
server.port: 8080
spring.datasource:
  url: jdbc:mysql://mysql/review-db
logging:
  level:
    root: INFO
    com.agosme: DEBUG